definitions:
  config:
    /hippo:configuration/hippo:roles/folderctxmenus-copy:
      jcr:primaryType: hipposys:role
      hipposys:privileges: ['folderctxmenus:copy']
    /hippo:configuration/hippo:roles/folderctxmenus-move:
      jcr:primaryType: hipposys:role
      hipposys:privileges: ['folderctxmenus:move']
    /hippo:configuration/hippo:roles/folderctxmenus-delete:
      jcr:primaryType: hipposys:role
      hipposys:privileges: ['folderctxmenus:delete']
    /hippo:configuration/hippo:roles/folderctxmenus-takeoffline:
      jcr:primaryType: hipposys:role
      hipposys:privileges: ['folderctxmenus:takeoffline']
    /hippo:configuration/hippo:roles/folderctxmenus-publishall:
      jcr:primaryType: hipposys:role
      hipposys:privileges: ['folderctxmenus:publishall']
    /hippo:configuration/hippo:roles/folderctxmenus-editor:
      jcr:primaryType: hipposys:role
      hipposys:privileges: ['folderctxmenus:copy', 'folderctxmenus:move', 'folderctxmenus:delete', 'folderctxmenus:takeoffline', 'folderctxmenus:publishall']
